## C1W1

### Neural Network

- X(입력)와 Y(출력)를 연결지어주는 함수를 찾는 과정
- 데이터가 많으면 많을수록 성능이 좋은 함수를 찾을 수 있음
- 해당 뉴런에 관련 없는 입력값이라도 입력해야 함
- **그 입력의 관계 여부, 가중치는 학습하면서 조절됨**

### NN 종류
- NN: 데이터베이스화된 데이터에 적합
- CNN: 이미지에 적함
- RNN: 오디오, 텍스트에 적합


### Data 종류
- 정형 데이터
    - 데이터베이스로 표현 가능
    - 정보의 특성 확정
- 비정형 데이터
    - 오디오, 텍스트, 이미지
    - 특징값을 추출하기 어려움
    - 딥러닝 기술 발전으로 판별 가능

### 최근에 들어 딥러닝이 발전한 계기
- 디지털 정보량의 증가, **컴퓨터 성능 향상**, 알고리즘 혁신
- Sigmoid --> ReLU로 activation function을 바꾸어 학습 속도 향상

## C1W2

### 신경망 학습방법
- 정방향 전파
- 역방향 전파

### Binary Classification(이진 분류)
- 1 or 0로 분류하는 것
- 연체를 했다 / 연체를 하지 않았다.
- 로지스틱 회귀(Logistic regression) 알고리즘 사용


### 표기
- $m$: 학습을 위한 데이터 세트 수
- ${(x^{(1)}, y^{(1)}), (x^{(2)}, y^{(2)}), ... (x^{(m)}, y^{(m)}), }$


- $n$: 입력 데이터 하나의 원소 개수
- $x$: 입력 데이터 하나
- $X$: 입력 데이터
- $X = \begin{bmatrix}
  x^{(1)}_1 & x^{(2)}_1 & \cdots & x^{(m)}_1 \\
  \vdots & \vdots & \ddots & \vdots \\
  x^{(1)}_n & x^{(2)}_n & \cdots & x^{(m)}_n
\end{bmatrix}$
- X.shape = (n, m)


- $y$: 출력 데이터 하나
- $Y$: 출력 데이터
- $Y = [y^{(1)}, y^{(2)}, ... y^{(n)}]$
- Y.shape = (1, m)


- $\hat{y}$: 예측값
- 0과 1 사이의 확률값으로 나타남


### Logistic regression(로지스틱 회귀)

![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwW1UGCC_OVB6IxMKkgUt2yftdHy4I2FqiMQ&usqp=CAU)

- 입력 특성(x)에 대한 실제값(y)을 가지고 예측값($\hat{y}$)을 구하고 그 예측값과 실제값의 오차가 최소가 되도록 하는 파라미터($W$, $b$)를 구해야 함

- $W$: $x$와 크기가 같은 $n$차원의 벡터
- $b$: 상수
- 예측값은 아래와 같이 구함

- $\hat{y} = \sigma(W^TX+b)$

### Sigmoid function


- $\sigma(z) = {1 \over 1 + e^{-z}}$
    - $z$가 클 수록 1로 수렴
    - $z$가 작을 수록 0으로 수렴
- 위 식에서 $\sigma$가 하는 역할은 예측값이 0에서 1사이가 되도록 만드는 역할

- Sigmoid 함수 그래프

![](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2Fcb3bEH%2Fbtq0UdlTEZz%2FfDeJKAzPlYkSs011P0fPt0%2Fimg.png)

- $\hat{y}$은 항상 0에서 1사이의 값을 가진다

### Loss Function(손실 함수)
- 한 세트에 대한 예측값($\hat{y}$)과 실제값($y$)의 오차를 구하는 함수

- $L(y, \hat{y}) = -(y\log{\hat{y}}+(1-y)\log(1-\hat{y}))$
- 실제값($y$)이 0이냐 1이냐에 따라서 오차를 구하는 식이 달라진다.
- $y=0$일 때: $L(y, \hat{y}) = -y\log{(1-\hat{y})}$
- $y=1$일 때: $L(y, \hat{y}) = -y\log{\hat{y}}$
- 그래프로 표현
- ![](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbsVKEL%2Fbtq0XQcqf19%2FdLQ59SVLirQbpARynqCPC0%2Fimg.png)


### Cost Function(비용 함수)
- 모든 입력세트에 대한 오차를 구하는 함수

- $J(W, b) = -{1 \over m}\sum_{i=1}^m(y^{(i)}\log{\hat{y}^{(i)}}+(1-y^{(i)})\log(1-\hat{y}^{(i)}))$

- 로지스틱 회귀 모델을 학습한다는 것은 비용 함수 $J$를 최소로 만드는 $W$와 $b$를 찾는 것을 의미

### 경사 하강법
- 비용함수의 값을 최소화하는 $w$와 $b$를 찾는데 사용할 수 있는 방법이다. 이때 비용함수는 볼록한(convex) 형태여야 한다. 만약 비용함수의 형태가 볼록하지 않다면 지역 최솟값을 여러 개 가지게 되어 진짜 최솟값을 찾기 어려워진다.
- 비용함수의 최솟값을 찾기 위한 시작점은 임의로 정하여도 상관없다. 경사 하강법을 사용하면 어디에서 시작하든 최솟값이 있는 곳으로 향하게 된다. 가파른 방향으로 한 스텝씩 업데이트하며 최솟값을 찾아간다.
- $w:=w-\alpha{\partial{J(w,b)}\over\partial{d}}$
- $b:=b-\alpha{\partial{J(w,b)}\over\partial{d}}$

![](https://builtin.com/sites/www.builtin.com/files/styles/ckeditor_optimize/public/inline-images/national/gradient-descent-convex-function.png)

- 로지스틱 회귀의 경사 하강법에서 for 문이 알고리즘을 비효율적으로 만듬 -> 벡터화를 통해 명시적 for 문을 제거

### 벡터화

- 벡터화를 사용하여 동시에 분산 처리

In [8]:
import numpy as np
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print(c)
print("Vectorized version: " + str(1000*(toc-tic)) + "ms")

250003.57277653238
Vectorized version: 0.49757957458496094ms


- for 문을 사용해서 순차적으로 계산

In [9]:
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("for loop: " + str(1000*(toc-tic)) + "ms")

250003.5727765315
for loop: 353.87134552001953ms


- 즉 벡터화를 사용한 코드의 시간이 훨씬 빠르다(0.49ms<<353.87ms) 

### 파이썬 브로드캐스팅
- 각 식자재 100g당 영양소가 가지는 칼로리 표

|            | Apples | Beef  | Eggs | Potatoes |
|------------|--------|-------|------|----------|
| Carb       | 56.0   | 0.0   | 4.4  | 68.0     |
| Protein    | 1.2    | 104.0 | 52.0 | 8.0      |
| Fat        | 1.8    | 135.0 | 99.0 | 0.9      |

- 브로딩캐스팅을 이용해 식자재 총 칼로리 중 각 영양소가 차지하는 비율을 구하는 예제

In [1]:
import numpy as np

A = np.array([[56, 0, 4.4, 68],
[1.2, 104, 52, 8],
[1.8, 135, 99, 0.9]])

cal = np.sum(A, axis=0)
percentage = 100*A/cal.reshape(1, 4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
